#pragma once

// ============================================================================
// SlaveTypeInfo.h — Slave type definitions derived from ESI XML.
//
// kSlaveTypes.cpp contains the actual data (auto-generated by
// scripts/parse_esi.py or hand-populated for known slave models).
//
// Each SlaveTypeInfo describes one product code with:
//   - Identity (vendor_id, product_code, type_name, human_name)
//   - DC operating modes (from ESI <Dc><OpMode> blocks)
//
// Lookup helpers (inline):
//   lookupSlaveType(vendor_id, product_code)  → const SlaveTypeInfo*
//   lookupDcMode(slave_info)                  → const DcOpMode*
// ============================================================================

#include <cstddef>
#include <cstdint>

namespace fc::ethercat {

// ---------------------------------------------------------------------------
// DcOpMode — one DC synchronisation operating mode from ESI XML.
// ---------------------------------------------------------------------------
struct DcOpMode {
    uint16_t    assign_activate; ///< Value for ecrt_slave_config_dc(); 0 = free-run
    const char* name;            ///< Short mode name, e.g. "DC", "DCIN", "Synchron"
    const char* desc;            ///< Human description, e.g. "DC-Synchron"
};

// ---------------------------------------------------------------------------
// SlaveTypeInfo — ESI-derived slave identity + DC mode table.
// ---------------------------------------------------------------------------
struct SlaveTypeInfo {
    uint32_t        vendor_id;
    uint32_t        product_code;
    const char*     type_name;       ///< e.g. "EL5151"
    const char*     human_name;      ///< e.g. "EL5151 1Ch. Inc. Encoder"
    const DcOpMode* dc_modes;        ///< nullptr if no DC support
    uint8_t         dc_mode_count;
};

// ---------------------------------------------------------------------------
// Slave type registry — populated by kSlaveTypes.cpp.
// ---------------------------------------------------------------------------
extern const SlaveTypeInfo kSlaveTypes[];
extern const size_t        kSlaveTypeCount;

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/// Return the SlaveTypeInfo for (vendor_id, product_code), or nullptr if unknown.
inline const SlaveTypeInfo* lookupSlaveType(uint32_t vid, uint32_t pc) {
    for (size_t i = 0; i < kSlaveTypeCount; ++i) {
        const auto& s = kSlaveTypes[i];
        if (s.vendor_id == vid && s.product_code == pc) return &s;
    }
    return nullptr;
}

/// Return the first DcOpMode with a non-zero assign_activate, or nullptr (= free-run only).
inline const DcOpMode* lookupDcMode(const SlaveTypeInfo* info) {
    if (!info || !info->dc_modes) return nullptr;
    for (uint8_t i = 0; i < info->dc_mode_count; ++i) {
        if (info->dc_modes[i].assign_activate != 0u) return &info->dc_modes[i];
    }
    return nullptr;
}

} // namespace fc::ethercat
